/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { IFeeCollector__factory } from "./IFeeCollector__factory";
export { ITenXBank__factory } from "./ITenXBank__factory";
export { Multicall__factory } from "./Multicall__factory";
