/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as abstract from "./abstract";
export type { abstract };
import type * as interfaces from "./interfaces";
export type { interfaces };
export type { DaiToken } from "./DaiToken";
export type { Multicall } from "./Multicall";
export type { TenXBank } from "./TenXBank";
