/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { IFeeCollector } from "./IFeeCollector";
export type { ITenXBank } from "./ITenXBank";
export type { Multicall } from "./Multicall";
